name: .NET Core Desktop

on: [push, pull_request]

jobs:

  build:
    runs-on: windows-latest

    env:
      Solution_Name: data-explorer-dotnet
      Test_Project_Path: tests

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Build app for release
      run: dotnet build --configuration Release

    - name: Execute unit tests
      run: dotnet test
